### ISSUE TITLE
Fail to print `measures`

### ISSUE THREAD

**Issue by willvieira** [ModelOriented/randomForestExplainer#19]
When generating the report with the function `explain_forest()`, the script fails to print the `measures` in the section "Compare importance measures".

I guess the problem is [here](https://github.com/ModelOriented/randomForestExplainer/blob/66fa7faf44f3bc5539516f43ee203ee11b5dc332/inst/templates/Explain_forest_template.Rmd#L92) as the object `measures` is not assigned nowhere in the document.

**Comment by Yue-Jiang** [comment]
Thanks for reporting! Indeed there's problem with that part of the code. Will fix soon.
