### ISSUE TITLE
Threshold values

### ISSUE THREAD

**Issue by RichardLaBrie** [ModelOriented/randomForestExplainer#23]
HI
I was wondering if it is possible to compute thresholds or pseudo-thresholds for each variable in the forest, similar to what single trees give. Something like the interaction grid where we sometimes see a clear value where the colors drastically change, but for all variables.

Thank you

**Comment by Yue-Jiang** [comment]
I'm not sure i understand the ask here - what is the threshold for? what is a pseudo-threshold? is there a reference you could point me to? or if you are looking for something like a p-value for variable importance (something like ranger::importance_pvalues)?

**Comment by RichardLaBrie** [comment]
I mean a threshold like in a regular tree. If x1< X, you go to the left branch, if x1 > X, you go the other way.
![image](https://user-images.githubusercontent.com/27828208/100484415-573bdc80-30ca-11eb-861f-709b413fa191.png)

**Comment by Yue-Jiang** [comment]
I see, although i'm not sure how to implement something like this for random forests as the trees would presumably have different thresholds for a given variable. the only thing i can think of is something like pdp or ale (for example, https://pbiecek.github.io/ema/ceterisParibus.html)
