### ISSUE TITLE
what is the meaning of “tree，variable ，minimal_depth”？

### ISSUE THREAD

**Issue by A-Pai** [ModelOriented/randomForestExplainer#25]
what is the meaning of “tree，variable ，minimal_depth”？
https://cran.rstudio.com/web/packages/randomForestExplainer/vignettes/randomForestExplainer.html

![image](https://user-images.githubusercontent.com/5112397/142765567-d306b1bc-ea3a-4232-b7e0-763ca00d6f7c.png)

**Comment by Yue-Jiang** [comment]
see https://cdn.staticaly.com/gh/geneticsMiNIng/BlackBoxOpener/master/randomForestExplainer_Master_thesis.pdf for details
