### ISSUE TITLE
what is the meaning of this figure？

### ISSUE THREAD

**Issue by A-Pai** [ModelOriented/randomForestExplainer#26]
what is the meaning of this figure？I couldn't understand it，especially what the arrow is pointing to
https://cran.rstudio.com/web/packages/randomForestExplainer/vignettes/randomForestExplainer.html
![image](https://user-images.githubusercontent.com/5112397/142765724-e9b25201-cbbd-444c-ae01-a1408b5f3198.png)

**Comment by Yue-Jiang** [comment]
see https://cdn.staticaly.com/gh/geneticsMiNIng/BlackBoxOpener/master/randomForestExplainer_Master_thesis.pdf for details
