### ISSUE TITLE
Adding Parallel processing capabilities to min_depth_distribution() function  

### ISSUE THREAD

**Issue by Aman-Basu** [ModelOriented/randomForestExplainer#34]
It would be great if parallel processing capabilities were added to the `min_depth_distribution()` function. The time required to get the output from `min_depth_distribution()` function is substantial for large complex models.

**Comment by mayer79** [comment]
I will make an attempt to make the function much faster (actually without using parallelism).

**Comment by mayer79** [comment]
Check above Pull Request

**Comment by mayer79** [comment]
Step towards faster calculations: https://github.com/ModelOriented/randomForestExplainer/pull/35
